## NOTE THIS CLASS IS AUTOGENERATED BY THE APIDOC GENERATOR
## TO CHANGE: script/apidoc/template/apidoc_controller.rb.erb and regenerate

class ApiController < ApplicationController
  
  def api
    render :action => request.path[1..-1].gsub(/\/$/, ""), :layout => "doc"
  end

end
